{% set name = "plux" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8daf4fbb02533d6dc709d011115ceb34ac5ded13e58492a3d08958fcb7d7a695

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pytest-runner
    - setuptools
    - wheel
  run:
    - python >=3.6
    - stevedore >=3.4

test:
  imports:
    - plugin
  commands:
    - python -c "import importlib.util; assert importlib.util.find_spec('plugin')"

about:
  home: https://github.com/localstack/plux
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Dynamic code loading framework used in LocalStack
  doc_url: https://pypi.org/project/plux/
  dev_url: https://github.com/localstack/plux

extra:
  recipe-maintainers:
    - raybellwaves
