{% set name = "plux" %}
{% set version = "1.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e335d0bb4b67e1cb18abce8b92370568394f75edfb8505398f51c577525467fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - stevedore >=3.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - plugin
  commands:
    - python -c "import importlib.util; assert importlib.util.find_spec('plugin')"

about:
  home: https://github.com/localstack/plux
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Dynamic code loading framework used in LocalStack
  doc_url: https://pypi.org/project/plux/
  dev_url: https://github.com/localstack/plux

extra:
  recipe-maintainers:
    - raybellwaves
