schema_version: 1

context:
  name: plux
  version: "1.16.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 226ed9dbb52f0ed64ee1969d541544e2e67af6da010b7ecebcf145c20e92245a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - pytest-runner
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - stevedore >=3.4

tests:
  - python:
      imports:
        - plux
      python_version:
        - '*'
        - ${{ python_min }}.*
      pip_check: true

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Dynamic code loading framework used in LocalStack
  homepage: https://github.com/localstack/plux
  repository: https://github.com/localstack/plux
  documentation: https://pypi.org/project/plux/

extra:
  recipe-maintainers:
    - raybellwaves
    - xhochy
